Path:
  iped_grid_name_ror: "docs/iped_grid_ror_backup.txt" # system
  high_cited_doi_concept: "docs/high_citedpaper_doi.txt" # system
  high_cited_doi: "docs/doi.txt" # system
  high_cited_doi_concept_level0: "docs/high_citedpaper_doi_level0.txt" # system
  universuty_type: "docs/school_type.txt" # system

WritePath:
  university_ori_FloderPath: "pro/experimentdata/universities/2020"
  university_dst_FloderPath: "pro/experimentdata/university_concepts/2020"
  



URL:
  entity: "works" # only support 'works' now
  mailto: "675589296@qq.com" # your mail
  per-page: "50" # return pages
  filter: "publication_year"
  year: "2013" 
  institutions: "ror"



DB:
  userName: "root"
  passWord: "xxxx"
  host: "127.0.0.1"
  port: 3306
  dbName: "test_db"