Path:
  iped_grid_name_ror: "docs/iped_grid_ror_backup.txt"
  high_cited_doi_concept: "docs/high_citedpaper_doi.txt"
  high_cited_doi: "docs/doi.txt"
  high_cited_doi_concept_level0: "docs/high_citedpaper_doi_level0.txt"
  university_ori_FloderPath: "pro/experimentdata/universities/2016"
  university_dst_FloderPath: "pro/experimentdata/university_concepts/2016"
  universuty_type: "docs/school_type.txt"



URL:
  entity: "works"
  mailto: "675589296@qq.com"
  per-page: "50"
  filter: "publication_year"
  year: "2011"
  institutions: "ror"



DB:
  userName: "root"
  passWord: "xxxx"
  host: "127.0.0.1"
  port: 3306
  dbName: "test_db"